### ISSUE TITLE
Catalog list image optimization not working in Magento 2.3.x

### ISSUE THREAD

**Issue by RicardsRikmanis** [fastly/fastly-magento2#282]
Hello, 

I've noticed that catalog list image optimization are not working since Magento 2.3.x. I've tested this on latest version of Fastly module (1.2.103). 

Looking at code I see that Fastly specific URL queries are added via `\Fastly\Cdn\Model\Product\Image` using `getUrl` which in turn is an override for `Magento\Catalog\Model\Product\Image`.

Problem is that in 2.3.x `Magento\Catalog\Model\Product\Image` is no longer used when generating catalog list images and image URL. Instead `Magento\Catalog\Model\View\Asset\Image` is used, which does not contain the Fastly image URL.

If it helps, the change to the used image class in Magento 2 core code was introduced via this commit https://github.com/magento/magento2/commit/da7a64f2585ac534762235821db727f7af59f808

**Comment by andriyShevtsov** [comment]
I also faced with similar issue

**Comment by andriyShevtsov** [comment]
@vvuksan We have internal Jira issue for this https://magento2.atlassian.net/browse/MAGECLOUD-3669

**Comment by vvuksan** [comment]
Fix has been released in 1.2.104

**Comment by RicardsRikmanis** [comment]
Hey @vvuksan I saw the fix. Its still missing parts of the original logic, like `canvas` parameter.

**Comment by vvuksan** [comment]
We'll look into it.

**Comment by vvuksan** [comment]
@RicardsRikmanis can you check the latest master to see if it fixes the issue ?

**Comment by RicardsRikmanis** [comment]
@vvuksan Yeah, it looks good now. Thank you
